### ISSUE TITLE
list of objects issue

### ISSUE THREAD

**Issue by MarcMielke** [movatechtoday/jsonnet_templating_language_support#1]
```
 tolerations: [
                { key: "my.io/compute", operator: "Equal", value: if $.placement.static then "static" else "ephemeral", effect: "NoSchedule" }  >>> , <<<
                { key: "my.io/purpose", operator: "Equal", value: if $.placement.static then "generic-static" else "generic", effect: "NoSchedule" },
            ],
```

No error indication if the comma after the first element in the list is missing. In my case our tooling accepted it too but silently used only the first element.

**Comment by movatechtoday** [comment]
Hello @MarcMielke 

Thank you for the open issue. Could you give more context here? What type of message do you expect? 

According to the Jsonnet specification, the code is valid. If no comma exists in the mentioned expression, the parser treats it as an object override, and two objects will be merged. That's why the parser doesn't treat it as an issue and doesn't emit errors or warnings here.

For more about merge behavior and its syntax, you can read here https://jsonnet.org/learning/tutorial.html in the Object-Orientation.

> The object composition operator +, which merges two objects, choosing the right hand side when fields collide

>  In the common case where you write foo + { ... }, i.e. the + is immediately followed by a {, then the + can be elided.


I can suggest adding a special inspection with the following behavior:

- check all object merge operations usages
- if there is an implicit merge operation, then highlight it with a message that 'implicit merge is used.'
- add a quick fix that changes it to the explicit object composition operator +, which merges two objects
-  if the object is inside an array then suggest `add comma between objects` 

Will it help you eliminate the issues you have encountered?

Kind Regards
MovaTech Today

**Comment by MarcMielke** [comment]
hey @movatechtoday - resolved in the meantime. ntl thx for your help, appreciated! it's indeed a jsonnet thing and not related to your plugin. best, marc
