### ISSUE TITLE
Not Compatible with the latest IntelliJ

### ISSUE THREAD

**Issue by MasslessParticle** [movatechtoday/jsonnet_templating_language_support#11]
![image](https://github.com/movatechtoday/jsonnet_pro/assets/1413241/920795c5-5308-41f5-9a76-0407d9be1564)

**Comment by Jezza** [comment]
Bump, is is a bit annoying as there's a bugfix in 2023.2 that I needed, so I had to upgrade, but that meant I lost Jsonnet.

Any progress regarding this would be amazing.

**Comment by Jezza** [comment]
@movatechtoday Any update?

**Comment by bcapitanu-asapp** [comment]
+1 please update to be compatible with latest IDE version!!!

**Comment by bvoss** [comment]
+1 please update

**Comment by bgaeddert** [comment]
+1 Please Update. Great Plugin!

**Comment by cyanblue792** [comment]
Great plugin, but it has been more than 3 weeks since the release of Intellij. If it takes this long to update a version tag (which is not even needed, the plugin can be configured to be marked as compatible for all future releases of the IDEs), maybe we are better off starting a new OSS plugin for jsonnet.

**Comment by movatechtoday** [comment]
Hello
Sorry for late response.
I am going to release an update next week. Approximately it should be available till Wednesday.
Sorry for inconveniences.

**Comment by MasslessParticle** [comment]
Looking forward to it. Thanks for the response!

**Comment by MasslessParticle** [comment]
Thanks again for the fix!
